Main svc compilations
no-vi-ka/java-explore-with-me-plus pull request #12
Opened 2024-12-15 16:26 UTC by no-vi-ka

Реализовала работу с compilations. В EventService добавила один метод для получения событий по списку id.

2024-12-16 22:19 UTC, elbonreedZ requested changes

2024-12-16 22:19 UTC, elbonreedZ commented on main-service/src/main/java/ru/practicum/compilation/service/CompilationServiceImpl.java
> +        compilation.setEvents(eventList);
преобразования можно выполнить в маппере

2024-12-16 22:19 UTC, elbonreedZ commented on main-service/src/main/java/ru/practicum/compilation/service/CompilationServiceImpl.java
> +    public List<CompilationDto> getAllCompilations(Boolean isPinned, Integer from, Integer size) {
Аргументов метода должно быть максимум два, то есть тут уже лучше упаковать. Или как вариант from и size в PAgeble сразу передавать. PageRequest.of(from / size, size) тут не нужно делить from / size, просто from. Но у этого метода другая большая проблема - n+1 запрос при присоединении events. Думаю, можно задуматься над join fetch

2024-12-16 22:19 UTC, elbonreedZ commented on main-service/src/main/java/ru/practicum/event/service/EventServiceImpl.java
> +        return eventRepository.findAllByIdIn(events);
Этот метод необязателен, он не несет дополнительной логики, можно прям с репозитория вызывать

2024-12-17 07:55 UTC, no-vi-ka commented on main-service/src/main/java/ru/practicum/event/service/EventServiceImpl.java
> +        return eventRepository.findAllByIdIn(events);
Сначала так и было) я подумала, что обращаться к чужому репозиторию как-то не очень правильно, что обычно вызов методов идёт через сервисы.

2024-12-17 07:59 UTC, no-vi-ka commented on main-service/src/main/java/ru/practicum/compilation/service/CompilationServiceImpl.java
> +        compilation.setEvents(eventList);
Маппер ведь интерфейс, реализующий мапстракт, как в него такую логику можно добавить. Если только сделать его обычным классом.
А получение events идёт и для преобразования в dto, и для записи в базе данных. Скорее вынесли преобразование в отдельный метод, так как он повторяется.

2024-12-17 08:01 UTC, no-vi-ka commented on main-service/src/main/java/ru/practicum/compilation/service/CompilationServiceImpl.java
> +    public List<CompilationDto> getAllCompilations(Boolean isPinned, Integer from, Integer size) {
Переделаю сегодня вечером

2024-12-17 19:39 UTC, no-vi-ka commented on main-service/src/main/java/ru/practicum/compilation/service/CompilationServiceImpl.java
> +        compilation.setEvents(eventList);
Вынесла в приватный метод, в любом случае, теперь эта часть кода не повторяется.

2024-12-17 19:42 UTC, no-vi-ka commented on main-service/src/main/java/ru/practicum/event/service/EventServiceImpl.java
> +        return eventRepository.findAllByIdIn(events);
Вернула его вызов из репозитория, а не из сервиса.

2024-12-17 19:42 UTC, no-vi-ka commented on main-service/src/main/java/ru/practicum/compilation/service/CompilationServiceImpl.java
> +    public List<CompilationDto> getAllCompilations(Boolean isPinned, Integer from, Integer size) {
Сделала по аналогии с теми исправлениями, которые внёс Даниил. Через создание отдельного класса CompilationParam.

2024-12-17 19:51 UTC, elbonreedZ commented on main-service/src/main/java/ru/practicum/compilation/service/CompilationServiceImpl.java
> +        compilation.setEvents(eventList);
передавать в метод маппера список событий

2024-12-17 19:53 UTC, elbonreedZ commented on main-service/src/main/java/ru/practicum/event/service/EventServiceImpl.java
> +        return eventRepository.findAllByIdIn(events);
ну вот кстати у меня по этому поводу в голове тоже путаница - к акому слою следует обращаться)))

2024-12-17 20:15 UTC, merged