CRUD операции с лайками.
no-vi-ka/java-explore-with-me-plus pull request #16
Opened 2024-12-21 12:43 UTC by no-vi-ka

Реализованы операции создания, изменения, удаления лайков пользователем. Получение осуществляется по id пользователя - просмотр всех его лайков.
Не трогала events в плане подсчёта рейтинга события и добавления поля с рейтингом в модель.

2024-12-22 16:52 UTC, elbonreedZ requested changes

2024-12-22 16:52 UTC, elbonreedZ commented on main-service/src/main/java/ru/practicum/rating/dto/NewRatingDto.java
> +    User user;
это поле здень не нужно, так так userId в pathvariable передается

2024-12-22 16:52 UTC, elbonreedZ commented on main-service/src/main/java/ru/practicum/rating/dto/NewRatingDto.java
> +    Event event;
ну а тут только event_id

2024-12-22 16:52 UTC, elbonreedZ commented on main-service/src/main/java/ru/practicum/rating/dto/NewRatingDto.java
> +    @NotBlank(message = "Поле mark не должно быть пустым.")
Not blank применяется только к строкам, соотвественно в event и user тоже не нужно использовать (но их и не должно быть в таком виде в каком сейчас)

2024-12-22 16:52 UTC, elbonreedZ commented on main-service/src/main/java/ru/practicum/rating/dto/RatingDto.java
> +    User user;
UserDto EventDto типы иначе ошибка lazy init

2024-12-22 16:52 UTC, elbonreedZ commented on main-service/src/main/java/ru/practicum/rating/dto/UpdateRatingDto.java
> +    @NotNull(message = "Поле id должно быть указано.")
в апдейт, как и в делит обычно указывают id в pathvariable

2024-12-22 16:52 UTC, elbonreedZ commented on main-service/src/main/java/ru/practicum/rating/dto/UpdateRatingDto.java
> +    User user;
изменить пользователя оставившего лайк нельзя

2024-12-22 16:52 UTC, elbonreedZ commented on main-service/src/main/java/ru/practicum/rating/dto/UpdateRatingDto.java
> +    @NotNull(message = "Поле status должно быть указано.")
вообще при обновлении поля могут быть пустыми - если пустое, то его не обновляем. Но так как это единственное поле которые можно обновить, то оставить можно

2024-12-22 16:52 UTC, elbonreedZ commented on main-service/src/main/java/ru/practicum/rating/mapper/RatingMapper.java
> +    Rating toRating(NewRatingDto newRatingDto);
тут сразу можно добавить Event event, User user в аргументы и соответсвующие аннотации

2024-12-22 16:52 UTC, elbonreedZ commented on main-service/src/main/java/ru/practicum/rating/service/RatingService.java
> +    RatingDto addRatingMark(long userId, @Valid NewRatingDto newRatingDto);
тут не нужна аннотация валид, в следующем тоже

2024-12-22 16:52 UTC, elbonreedZ commented on main-service/src/main/java/ru/practicum/rating/service/RatingServiceImpl.java
> +//        if (!ratingRepository.findAllByUser(user).stream()
оно кстати проще делается например метод existsByUser_IdAndEvent_Id

2024-12-22 16:52 UTC, elbonreedZ commented on main-service/src/main/java/ru/practicum/rating/service/RatingServiceImpl.java
> +//        }
и нужно провреить существование event

2024-12-22 16:52 UTC, elbonreedZ commented on main-service/src/main/java/ru/practicum/rating/service/RatingServiceImpl.java
> +//        }
и задать ивент

2024-12-22 16:52 UTC, elbonreedZ commented on main-service/src/main/java/ru/practicum/rating/service/RatingServiceImpl.java
> +    public void removeRatingMark(long userId, long ratingId) {
мне кажется тут не требуются такие проверки, лишний раз запросы отправлять. Если очень хочется проверить юсера, то можно сделать кастомный метод deleteByIdAndUser_Id @Modifying @Transactional

2024-12-23 21:21 UTC, no-vi-ka commented on main-service/src/main/java/ru/practicum/rating/service/RatingServiceImpl.java
> +//        if (!ratingRepository.findAllByUser(user).stream()
Прописать ограничение в таблице мне кажется тоже достаточно просто.

2024-12-23 21:40 UTC, no-vi-ka commented on main-service/src/main/java/ru/practicum/rating/service/RatingService.java
> +    RatingDto addRatingMark(long userId, @Valid NewRatingDto newRatingDto);
Здесь я написала вызов метода в контроллере и нажала создать его в сервисе, при этом скопировалась аннотация. Да, забыла её удалить.

2024-12-26 18:16 UTC, EyesHead approved these changes

2025-01-12 04:12 UTC, merged